-- liquibase formatted sql
-- changeset salmanTer:1
CREATE TABLE if not exists shelter  (
    id bigint generated by default as identity primary key,
    name text not null,
    info text not null,
    regime text not null
)

--changeset salmanTer:2
CREATE TABLE if not exists caretaker  (
    id bigint generated by default as identity primary key,
    chat_id bigint not null,
    name text not null,
    address text not null,
    day_of_getting_pet bigint,
    on_probation boolean
)

--changeset salmanTer:3
ALTER TABLE shelter
ADD address text;

--changeset salmanTer:4
ALTER TABLE caretaker
add passport text;

--changeset salmanTer:5
CREATE TABLE if not exists caretaker_avatar (
 id bigint generated by default as identity primary key,
 file_path text not null,
 media_type text not null,
 file_size bigint not null,
 data OID not null
)