-- liquibase formatted sql
-- changeset salmanTer:1
CREATE TABLE if not exists shelter  (
    id bigint generated by default as identity primary key,
    name text not null,
    info text not null,
    regime text not null
)

--changeset salmanTer:2
CREATE TABLE if not exists caretaker  (
    id bigint generated by default as identity primary key,
    chat_id bigint not null,
    name text not null,
    address text not null,
    day_of_getting_pet bigint,
    on_probation boolean
)
